import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Captures a DOM element and saves it as an A4 landscape PDF.
 * @param elementId  - id of the DOM element to capture
 * @param filename   - output filename (without extension)
 * @param title      - optional title printed at the top of the PDF
 */
export async function exportTimetablePdf(
  elementId: string,
  filename: string,
  title?: string
): Promise<void> {
  const element = document.getElementById(elementId);
  if (!element) {
    console.error(`Element #${elementId} not found`);
    return;
  }

  // Capture at 2× for sharpness
  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    backgroundColor: '#ffffff',
    logging: false,
  });

  const imgData = canvas.toDataURL('image/png');

  // A4 landscape: 297 × 210 mm
  const pdf = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Print title
  if (title) {
    pdf.setFontSize(13);
    pdf.setTextColor(80, 40, 160);
    pdf.text(title, 14, 14);
  }

  const topMargin = title ? 20 : 10;
  const availableHeight = pageHeight - topMargin - 10;
  const availableWidth = pageWidth - 20;

  // Scale image to fit page while preserving aspect ratio
  const imgRatio = canvas.width / canvas.height;
  let imgW = availableWidth;
  let imgH = imgW / imgRatio;
  if (imgH > availableHeight) {
    imgH = availableHeight;
    imgW = imgH * imgRatio;
  }

  const xOffset = (pageWidth - imgW) / 2;
  pdf.addImage(imgData, 'PNG', xOffset, topMargin, imgW, imgH);

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text(
    `Generated by ITMS · ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 5,
    { align: 'center' }
  );

  pdf.save(`${filename}.pdf`);
}
